### PR TITLE
Liste d'organisations Github et OSS

### PR DESCRIPTION
**Pull request by smellems**
Add a ORGS.md file to list the GC Github (and other code repos) open source organizations.

### CODE REVIEW

**Comment by nschonni** [comment]
https://github.com/github/government.github.com/blob/9252298d8fe4bf8645681e09fcb10d041958a75f/_data/governments.yml#L89 has a more complete list, but doesn't include the BitBucket. It also looks like it's missing CSEC and then new TBS-SCT orgs which I'll PR there now

**Comment by patcon** [comment]
user-facing link: https://government.github.com/community/#canada

**Comment by patcon** [comment]
Maybe modify this ORGS.md file to link there, and supplement it with any other bitbucket orgs?

**Comment by jpmckinney** [comment]
@patcon government.github.com doesn't aggregate the federal repositories together - it's just one big bucket for federal, provincial, territorial, municipal. The Markdown file in this repo can (1) only just federal organizations and (2) maybe eventually provide a big more more prose about each organization.

**Comment by jpmckinney** [comment]
FYI, @nschonni's PRs: https://github.com/github/government.github.com/pulls/nschonni

**Comment by patcon** [comment]
EDIT: was writing this before @jpmckinney replied, and perhaps not as relevant anymore.

---------------------------

Alternatively, github does offer the ability to mirror, in a way that is [shown visually](https://imgur.com/GzEtrNy.png) on the repo page.

In the [docs](https://help.github.com/articles/about-github-mirrors/) they suggest managing it yourself, but I don't think that will show it visually. In the past, I had set up a mirror for [fdroid](https://github.com/f-droid/fdroidclient) by communicating with github support over email, and cc'ing one of the project maintainers to assure github that it was alright. I've confirmed in [a demo repo](https://github.com/test-apogy/ca.gc.asc_csa.apogy) that using [this linked method](https://help.github.com/articles/duplicating-a-repository/#mirroring-a-repository) doesn't allow us to do this ourselves, so we're still in the position where someone would need to broker that mirroring with github support.

The downside is that it only works for mirroring specific repos, so every time CSA adds a new repo to their bitbucket org, someone would need to correspond with github to get it mirrored.

**Pull request merged**
